position = [ 47.385, 32.1575 ]
is_flipped = false
has_model = true
is_tht_or_smd = true
has_paste = true
pad_type = "SMD"
shape = "RECT"
size = [ 3.5, 1.6 ]
rotation = 1.5707963267948966
roundness = 0.25
drill_shape = "OVAL"
drill_size = [ 0.0, 0.0 ]
fab_type = "NONE"
